NAME	=	a.test
CXX		=	c++

FLAGS	=	-Wall
FLAGS	+=	-Wextra
FLAGS	+=	-Werror
FLAGS	+=	-std=c++98

SRCDIR	=	.
OBJDIR	=	objs

SRCS	=	$(wildcard $(SRCDIR)/*.cpp)
HEADERS =	$(wildcard $(SRCDIR)/*.hpp)

OBJS	=	$(patsubst $(SRCDIR)/%.cpp,$(OBJDIR)/%.o,$(SRCS))


#***************************************************#
#*						RULES						#
#***************************************************#


all: ${NAME}

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp $(HEADERS)
	@mkdir -p $(OBJDIR)
	$(CXX) $(FLAGS) -c $< -o $@

${NAME}: ${OBJS}
	$(CXX) $(FLAGS) ${OBJS} -o $@

clean:
	@rm -rf ${OBJDIR}		

fclean: clean
	rm -f ${NAME}

re: fclean ${NAME}

.PHONY: all clean fclean re